added check  for sane .hc directory. Fixed bug when not copying from skeleton

diff --git a/bin/holochain.app.init b/bin/holochain.app.init
--- a/bin/holochain.app.init
+++ b/bin/holochain.app.init
@@ -35,7 +35,11 @@ printf "\nHC:       machine name: \"$machineName\""
 echo
 holochain.tools.confirm.y "Is this correct? (Y/n)" || { echo "terminated by user" && exit 1 ; } && :
 
-{ [[ ! -z $copyAppDir ]] && cp $HOLOCHAIN_SYSTEM_BIN/../examples/$copyAppDir/* -r . && echo "HC: copied example app from: $copyAppDir" ; } || { echo "HC: failed to copy example app content from $copyAppDir. Exiting" && exit 1 ; }
+if [ ! -z $copyAppDir ] ; then
+ { cp $HOLOCHAIN_SYSTEM_BIN/../examples/$copyAppDir/* -r . && echo "HC: copied example app from: $copyAppDir" ; } || { echo "HC: failed to copy example app content from $copyAppDir. Exiting" && exit 1 ; }
+else
+  :
+fi
 
 mkdir .hc
 cd .hc
